export default function Index() {
  return (
    <div>
      <Head>
        <title>Документация</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}